<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tienda</title>
</head>
<body>

    <a href="index.php?var=registro">Registrarse</a>
    <a href="index.php?var=login">Iniciar sesion</a>

    <br><br>

    <?php

        if (isset($_GET['var'])) {
            $opcion = $_GET['var'];
        }else{
            $opcion = 'registro';
        }

        if ($opcion == 'registro') {
            echo '<h1>Registro</h1>';
            echo '<form action="index.php?var=registro" method="POST">';
            echo '<input type="text" name="nombre" placeholder="Nombre">';
            echo '<input type="text" name="email" placeholder="Email">';
            echo '<input type="password" name="password" placeholder="Contraseña">';    
        }else if ($opcion == 'login') {
            echo '<h1>Login</h1>';
            echo '<form action="index.php?var=login" method="POST">';
            echo '<input type="text" name="email" placeholder="Email">';
            echo '<input type="password" name="password" placeholder="Contraseña">';    
        }else {
            echo '<h1>Opcion no valida</h1>';   
        }

    ?>
</body>
</html>
